// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKeY5bmgoOrCPH_QRzp4gmgKVi7eyJWJ0',
    appId: '1:561065428018:web:3dc1a3b31d8c673831682b',
    messagingSenderId: '561065428018',
    projectId: 'meusgastos-b235b',
    authDomain: 'meusgastos-b235b.firebaseapp.com',
    storageBucket: 'meusgastos-b235b.firebasestorage.app',
    measurementId: 'G-Z237GVQ80S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZI_R5o9ixJJZnlAXiIhG4R_MUs9pqrAk',
    appId: '1:561065428018:android:50b6903fff83d00631682b',
    messagingSenderId: '561065428018',
    projectId: 'meusgastos-b235b',
    storageBucket: 'meusgastos-b235b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgJ9GUCiPtSbcMYsq5cGBz3xf4bljIdAI',
    appId: '1:561065428018:ios:723d19785dcdbd6631682b',
    messagingSenderId: '561065428018',
    projectId: 'meusgastos-b235b',
    storageBucket: 'meusgastos-b235b.firebasestorage.app',
    iosBundleId: 'meusgastos.myapp',
  );
}
